config/routes.rb
Rails.application.routes.draw do

  get 'feeds/index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'stories#index'
  get 'dashboard'  => 'dashboard#index'

  resources :stories do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :user

end

app/models/story.rb
class Story < ApplicationRecord
  validates :title, :content, :all_tags, presence: true
  has_many :comments, as: :commentable
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(',')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagging
  has_many :stories, through: :tagging
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :story
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :comments
end

app/controllers/Comments_Controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @commentable = @commentable.comments.new(comment_params)
    if @commentable.save
      redirect_to :back, notice: 'Your comments are posted.'
    else
      redirect_to :back, notice: 'Your comments could not posted.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
  end
end

app/controllers/Stories_Controller.rb
class StoriesController < ApplicationController
  def index
    #@stories = Story.all
    @stories = Story.paginate(:page => params[:page])
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user_id = current_user.id
    if @story.save
      flash[:success] = 'Stoy added successfully.'
      redirect_to @story
    else
      flash[:error] = 'Could not add Story. Please try later.'
      redirect_to @story
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :content, :all_tags)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user && current_user.is_admin
      flash[:success] = "logged in successfully"
      return feeds_index_path
    else
      flash[:success] = "logged in successfully."
      return stories_path
    end
  end

  helper_method :resource_name, :resource, :devise_mapping

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email,
    :password, :password_confirmation) }
    update_attrs = [:password, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email,
    :password, :remember_me) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @commentable = @commentable.comments.new(comment_params)
    if @commentable.save
      redirect_to :back, notice: 'Your comments are posted.'
    else
      redirect_to :back, notice: 'Your comments could not posted.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @stories = current_user.stories
  end
end

app/controllers/registrations_controller.rb
 class RegistrationsController < Devise::RegistrationsController
  respond_to :html, :json

  # Signs in a user on sign up. You can overwrite this method in your own
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
    flash[:notice] = "Sign up successfully."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :html, :js
  before_filter :handle_redirect, :if => Proc.new { |c| c.request.format == :json }

  def create
    resource = warden.authenticate!(auth_options)
    sign_in_and_redirect(resource_name, resource)
    flash[:notice] = "logged in successfully."
    binding.pry
  end

  # def sign_in_and_redirect(resource_or_scope, resource=nil)
  #   scope = Devise::Mapping.find_scope!(resource_or_scope)
  #   resource ||= resource_or_scope
  #   sign_in(scope, resource) unless warden.user(scope) == resource
  #   flash[:notice] = "Logged in successfully."
  #   flash.keep(:notice)
  #   # if current_user && current_user.is_admin
  #   #   render js: "window.location = #{dashboard_path.to_json}"
  #   # else
  #     render js: "window.location = #{stories_path.to_json}"
  #   # end
  #   binding.pry
  # end

  def failure
    warden.custom_failure!
    render json: { success: false, error: I18n.t("devise.failure.#{env['warden'].message.to_s}") }, status: 401
  end

  protected

  def auth_options
    {:scope => resource_name, :recall => "#{controller_path}#failure"}
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    #@stories = Story.all
    @stories = Story.paginate(:page => params[:page])
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user_id = current_user.id
    if @story.save
      flash[:success] = 'Stoy added successfully.'
      redirect_to @story
    else
      flash[:error] = 'Could not add Story. Please try later.'
      redirect_to @story
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :content, :all_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>
  <%= form_for [comment, Comment.new] do |f| %>
    <div class ="form-group">
      <%= f.text_area :body, :class => "form-control", placeholder: "Add a Reply"%>
    </div>
    <%= f.submit "Reply", class: 'btn btn-info pull-right' %>
    <% end %><br><br>
  <ul>
    <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/dashboard/index.html.erb
<div class="container">
    <h2 class="text-center header_color">Admin Dashboard</h2><hr>
    <div class="col-lg-12">
      <div class="col-lg-3 col-sm-6  col-xs-12">
        <a href="/users"  class="tiles_text">
          <div class="thumbnail tile tile-medium  tiles_background_color_blue  dashboard_thumb_img">
            <p>Manage Users</p>
          </div>
        </a>
      </div>
      <div class="col-sm-6 col-lg-3 col-xs-12">
        <a href="/stoies"  class="tiles_text">
          <div class="thumbnail tile tile-medium  tiles_background_color_green  dashboard_thumb_img">
            <p>Manage Stories</p>
          </div>
        </a>
      </div>
      <div class="col-sm-6 col-lg-3 col-xs-12">
        <a href="/stoies"  class="tiles_text">
          <div class="thumbnail tile tile-medium  tiles_background_color_yellow  dashboard_thumb_img">
            <p>Manage Destinations</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-lg-12 col-sm-12 col-xs-12 ">
      <div class="col-sm-6 col-lg-3 col-xs-12">
        <a href="/stoies"  class="tiles_text">
         <div class="thumbnail tile tile-medium tile tiles_background_color_carot  dashboard_thumb_img">
          <p>Manage Monuments</p>
        </div>
      </a>
    </div>
    <div class="col-sm-6 col-lg-3 col-xs-12">
     <a href="/stoies"  class="tiles_text">
       <div class="thumbnail tile tile-medium  tiles_background_color_greensea  dashboard_thumb_img">
        <p>Manage Queries</p>
      </div>
    </a>
  </div>
</div>

app/views/feeds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <% @stories.each do |story|%>
        <h3><%= link_to(story.title, story_path(story)) %></h3>
        <%= story.content.html_safe %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bd-footer text-muted"">
  <div class = "container">
    <div class ="row col-md-offset-2">
      <div class="col-lg-2">
         <h5 class="font-weight-bold">
            <strong>Home</strong>
        </h5>
      </div>
      <div class="col-lg-2">
          <h5 class="font-weight-bold">
              <strong>Products</strong>
          </h5>
      </div>
      <div class="col-lg-2">
        <h5 class="font-weight-bold">
            <strong>Useful links</strong>
        </h5>
      </div>
      <div class="col-lg-2">
        <h5 class="font-weight-bold">
            <strong>Contact</strong>
        </h5>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="/">Home</a></li>
        <li><a href="#"></a></li>
        <li><a href="#"></a></li>
        <li><a href="#"></a></li>
        <li><a href="#"></a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user.is_admin %>
          <li><a href="/dashboard"><span class="glyphicon glyphicon-user"></span>Dashboard</a></li>
        <% end %>
        <li><a href="/stories/new"><span class="glyphicon glyphicon-user"></span>New Story</a></li>
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Logout", destroy_user_session_path,  method: :delete  %></li>
          </ul>
        </li>
        <% else %>
          <li><a href="" data-toggle="modal" data-target="#signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="#" data-toggle="modal" data-target="#signin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= render 'layouts/signin_modal' %>
<%= render 'layouts/signup_modal' %>

<script type="text/javascript">
  // this makes sure only one model visiable at a time
  var modalUniqueClass = ".modal";
  $('.modal').on('show.bs.modal', function(e) {
    var $element = $(this);
    var $uniques = $(modalUniqueClass + ':visible').not($(this));
    if ($uniques.length) {
      $uniques.modal('hide');
      $uniques.one('hidden.bs.modal', function(e) {
        $element.modal('show');
      });
      return false;
    }
  });

  // singup process
  $(document).on('click', '#sign_up_button', function() {
    $("#signup").toggleClass("is-active");
    $("form#sing_up").bind("ajax:success", function(e, data, status, xhr) {
    if (data.success) {
          $("#registration1").toggleClass("is-active");
          window.location.reload();
      } else {
        return   console.log("I am in else")
    }
      }).bind("ajax:complete", function(e, xhr, status, error) { // <----
        if (xhr.status != 201) {  // probable Devise timeout
        var error_messages;
        error_messages = xhr.responseJSON['error'] ? "<div class='alert alert-danger pull-left'>" + xhr.responseJSON['error'] + "</div>" : xhr.responseJSON['errors'] ? $.map(xhr.responseJSON["errors"], function(v, k) {
        return "<div class='alert alert-danger pull-left'>" + k + " " + v + "</div>";
        }).join("") : "<div class='alert alert-danger pull-left'>Unknown error</div>";
        $('.messages').html(error_messages);
        }
      if (xhr.status == 201) {
        window.location.reload();
      }
    });
  });

  //handle login process on client/server side
  $(document).on('click', '#sign_in_button', function() {
    $("#Login").toggleClass("is-active");
    $("form#login_form").bind("ajax:success", function(e, data, status, xhr) {
      if (data.success) {
        $("#Login").toggleClass("is-active");
        $('.success').html('logged in successfully');
      } else {
        return console.log('failure!');
      }
    }).bind("ajax:complete", function(e, xhr, status, error) { // <----
      if (xhr.status == 401) {  // probable Devise timeout
        $('.messages').html('Invalid email or password');
        }
    });
  });
</script>

app/views/layouts/_signin_modal.html.erb
<!-- login Modal -->
<div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel">Sign in</h3>
        <div class="text-center">
          New here?
          <a href="" data-toggle="modal" data-target="#signup" class="text-center">Sign up</a>
        </div>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:id => "login_form" }, :format => :json, :remote => true ) do |f| %>
          <div class="messages text-center"></div>
          <div class="success-messages text-center"></div>
          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, class: 'form-control' %>
          </div>

           <div class="form-group">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
          </div>

          <div class="col-lg-12 form-group">
            <div class="col-lg-4 remember-me">
              <% if devise_mapping.rememberable? -%>
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              <% end -%>
            </div>
            <div class="col-lg-4 pull-right">
              <div class="form-group">
                  <a href="/users/password/new">Forgot your password?</a>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.submit "SIGN IN", id: 'sign_in_button', class: 'btn btn-primary form-control' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<!-- Sign up Modal -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Sign up</h4>
        <div class="text-center">
          Already a member?
          <a href="" data-toggle="modal" data-target="#signin" class="text-center">Sign in</a>
      </div>
      </div>

      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name),validate: true, :html => { :id => "sing_up",:'data-type' => 'json' }, :format => :json, :remote => true ) do |f| %>
          <%= devise_error_messages! %>

         <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, class: 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class: 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.submit "Sign up", class: 'btn btn-primary form-control' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profile</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-warning alert-dismissible-<%= key %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </div><br>
  <%= render 'layouts/footer' %>
</html>

app/views/stories/_new.html.erb
<%= form_for @story,validate: true do |f|%>
  <div class ="form-group">
    <%= f.text_field :title, :class => "form-control", :placeholder => "Add Title" %>
  </div>
  <div class ="form-group">
    <%= f.cktext_area :content, :class => "form-control", :placeholder => "Add Content", rows: 15, cols: 25 %>
  </div>
   <div class ="form-group">
    <%= f.text_field :all_tags, :class => "form-control", :placeholder => "Add Tag(s)" %>
  </div>
  <%= f.submit "Submit", class: 'btn btn-primary pull-right' %>
<% end %>

app/views/stories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <% @stories.each do |story|%>
        <h3><%= link_to(story.title, story_path(story)) %></h3>
        <%= story.content.html_safe %>
      <% end %>
    </div>
    <%= will_paginate @stories %>
    <div class="col-lg-3">
      Categoies
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<div class ="container">
  <div class ="row col-md-offset-1">
    <h3>Add a Story</h3>
    <div class ="col-lg-9">
      <%= render 'new'%>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 col-md-offset-1">
		  <h2><%= @story.title %></h2><br>
			<%= @story.content.html_safe %>
			<h3>Comments</h3>
		  <%= form_for [@story, Comment.new] do |f| %>
		  	<%= f.text_area :body, :class => "form-control", :placeholder => "Add Comment" %><br>
		  <%= f.submit "Comment", class: 'btn btn-primary pull-right' %>
		  <% end %><br><br>
			<ul>
				<%= render(partial: 'comments/comment', collection: @story.comments) %>
			</ul>
		</div>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>